# Generated by Django 6.0.2 on 2026-02-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='team_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
