# Generated by Django 6.0.2 on 2026-02-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_application_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
