# Generated by Django 6.0.2 on 2026-02-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_match_position_match_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
