# Generated by Django 6.0.2 on 2026-02-24 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_match_score1_match_score2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='score1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='score2',
        ),
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='tournaments.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='next_slot',
            field=models.CharField(blank=True, choices=[('a', 'team_a'), ('b', 'team_b')], max_length=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='tournaments.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='tournaments.team'),
        ),
    ]
