# Generated by Django 6.0 on 2026-03-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0004_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='triggerbot_configs/')),
            ],
        ),
        migrations.DeleteModel(
            name='Script',
        ),
    ]
