# Generated by Django 6.0.2 on 2026-02-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_product_subscription_options_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('services', 'Services'), ('accounts', 'Accounts')], default='services', max_length=32),
        ),
    ]
