# Generated by Django 6.0.2 on 2026-02-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('services', 'Services'), ('accounts', 'Accounts')], default='services', max_length=32),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
