# Generated by Django 6.0.1 on 2026-02-22 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_set_stock_for_account_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crosshair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('crosshair_code', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='crosshairs/main/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copies_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-copies_count', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
        migrations.CreateModel(
            name='CrosshairImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='crosshairs/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crosshair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.crosshair')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
