# Generated by Django 6.0.2 on 2026-03-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_crosshair_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crosshairimage',
            name='crosshair',
        ),
        migrations.DeleteModel(
            name='Crosshair',
        ),
        migrations.DeleteModel(
            name='CrosshairImage',
        ),
    ]
